name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Trigger this workflow when code is pushed to the 'main' branch
    paths:
      - '**/*'  # Only trigger for changes to Python files (or adjust for your app's language)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code from GitHub
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Docker Buildx (optional for advanced builds)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Log into Docker Hub or Amazon ECR
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build the Docker image and tag it
    - name: Build Docker image
      run: |
        docker build -t my-docker-image:${{ github.sha }} .

    # Push the Docker image to a registry
    - name: Push Docker image to Docker Hub
      run: |
        docker push my-docker-image:${{ github.sha }}
